### Get all contests
GET http://localhost:4000/api/contests

### Get one contest by id
GET http://localhost:4000/api/contests/5de40035916801026c7223a3

### Create new contest
POST http://localhost:3000/contests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGQ5MTc1MTQ2YjJiYTJmMDRmZmY0YjIiLCJuYW1lIjoiTHVrYXMiLCJzdXJuYW1lIjoiS3J1cGVua2luYXMiLCJhZ2UiOjIyLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHVGVXdnMnRNNTlPQVB5QnNYUlZyb09yUld3RXJQS2JJRDExT0NpSWhNdkRQWi4yS1ZGTVBPIiwiYWRtaW4iOnRydWUsImlhdCI6MTU3NTgzMjg0OSwiZXhwIjoxNTc1ODMzMjA5fQ.vtDqXTncwH8Bq3TrN5Y_QzloGLEc3x4qCN8lIe4znhE
Content-Type: application/json

{
    "title": "Konkursas 3",
    "about": "1 etapo konkursas"
}

### Delete contest by id
DELETE http://localhost:3000/contests/5de40035916801026c7223a3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGU0MDU0YzM2MzM5ZDQ2YzgwMGQwMWEiLCJuYW1lIjoiTHVrYXMiLCJzdXJuYW1lIjoiS3J1cGVua2luYXMiLCJhZ2UiOjIyLCJlbWFpbCI6ImFkbWluMkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRGMEhGWDR5dGFXMDlNdkVycTdmWndla3l1bWl5LkhFYWpDWGo5WlQzNDdHVFd0ZE9tVEFHRyIsImFkbWluIjp0cnVlLCJpYXQiOjE1NzU4MzM1MTcsImV4cCI6MTU3NTgzMzg3N30.2MEcn7MpWSM0oCuRLzRFgLGLlRhCO1caDWPMb_4bEBg

### Update contest by id
PATCH http://localhost:3000/contests/5de40035916801026c7223a3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGU0MDU0YzM2MzM5ZDQ2YzgwMGQwMWEiLCJuYW1lIjoiTHVrYXMiLCJzdXJuYW1lIjoiS3J1cGVua2luYXMiLCJhZ2UiOjIyLCJlbWFpbCI6ImFkbWluMkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRGMEhGWDR5dGFXMDlNdkVycTdmWndla3l1bWl5LkhFYWpDWGo5WlQzNDdHVFd0ZE9tVEFHRyIsImFkbWluIjp0cnVlLCJpYXQiOjE1NzU4MzM1MTcsImV4cCI6MTU3NTgzMzg3N30.2MEcn7MpWSM0oCuRLzRFgLGLlRhCO1caDWPMb_4bEBg
Content-Type: application/json

{
    "title": "Konkursas"
}