### Get all forms
GET http://localhost:4000/api/forms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGQ5MTc1MTQ2YjJiYTJmMDRmZmY0YjIiLCJuYW1lIjoiTHVrYXMiLCJzdXJuYW1lIjoiS3J1cGVua2luYXMiLCJhZ2UiOjIyLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHVGVXdnMnRNNTlPQVB5QnNYUlZyb09yUld3RXJQS2JJRDExT0NpSWhNdkRQWi4yS1ZGTVBPIiwiYWRtaW4iOnRydWUsImlhdCI6MTU3NzExNTE2MywiZXhwIjoxNTc3MTE4MTYzfQ.bY2ehM2s-NFgeSmWorCIQlkcdIzexJZ66XVx8SXYmI0

### Get one form by id
GET http://localhost:3000/forms/5deba19b15117818906b5d0d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGUyNzEzOWYyNTA1OTNkODRhZjQzNTMiLCJuYW1lIjoiVG9tYXMiLCJzdXJuYW1lIjoiTWFsaW5hdXNrYXMiLCJhZ2UiOjMwLCJlbWFpbCI6InN1dUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRQMTYweFRoaFMvMjdMWElCR243ejR1Qm5JUzNaNzF5ME15TGUwcEl1dFl6SEpZRG5XWG1LcSIsImFkbWluIjpmYWxzZSwiaWF0IjoxNTc1OTYyNTc1LCJleHAiOjE1NzU5NjI5MzV9.sv5X0IjR146eEl73SMymfoDWWu2CXFlJGAiYAoYwMoU
### Create new form
POST http://localhost:3000/forms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGUyNzEzOWYyNTA1OTNkODRhZjQzNTMiLCJuYW1lIjoiVG9tYXMiLCJzdXJuYW1lIjoiTWFsaW5hdXNrYXMiLCJhZ2UiOjMwLCJlbWFpbCI6InN1dUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRQMTYweFRoaFMvMjdMWElCR243ejR1Qm5JUzNaNzF5ME15TGUwcEl1dFl6SEpZRG5XWG1LcSIsImFkbWluIjpmYWxzZSwiaWF0IjoxNTc1NzIzNDk2LCJleHAiOjE1NzU3MjM4NTZ9.1XwhQS1ZP8KnIFj0b5OQauPvPesAQahEisNzeMaiS30
Content-Type: application/json

{
    "city": "Kaunas",
    "address": "Zveryno g. 17",
    "phone": "37062524123",
    "about": "L"
}

### Delete form by id
DELETE http://localhost:3000/forms/5deba19b15117818906b5d0d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGQ5MTc1MTQ2YjJiYTJmMDRmZmY0YjIiLCJuYW1lIjoiTHVrYXMiLCJzdXJuYW1lIjoiS3J1cGVua2luYXMiLCJhZ2UiOjIyLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHVGVXdnMnRNNTlPQVB5QnNYUlZyb09yUld3RXJQS2JJRDExT0NpSWhNdkRQWi4yS1ZGTVBPIiwiYWRtaW4iOnRydWUsImlhdCI6MTU3NTcyNjY5MywiZXhwIjoxNTc1NzI3MDUzfQ.5xhzcVZ-r5hJR8EzWFlF1sWIi9SNWZgWCryFPU1yw6M

### Update form by id
PATCH http://localhost:3000/forms/5deba19b15117818906b5d0d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGQ5MTc1MTQ2YjJiYTJmMDRmZmY0YjIiLCJuYW1lIjoiTHVrYXMiLCJzdXJuYW1lIjoiS3J1cGVua2luYXMiLCJhZ2UiOjIyLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHVGVXdnMnRNNTlPQVB5QnNYUlZyb09yUld3RXJQS2JJRDExT0NpSWhNdkRQWi4yS1ZGTVBPIiwiYWRtaW4iOnRydWUsImlhdCI6MTU3NTcyNjY5MywiZXhwIjoxNTc1NzI3MDUzfQ.5xhzcVZ-r5hJR8EzWFlF1sWIi9SNWZgWCryFPU1yw6M
Content-Type: application/json

{
    "city": "Siauliai",
    "address": "Gedimino g. 48",
    "phone": "37062214256"
}