### Get all prizes
GET http://localhost:3000/prizes

### Get one prize by id
GET http://localhost:3000/prizes/5de402c2cde1de14602ed277

### Create new prize
POST http://localhost:4000/prizes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGQ5MTc1MTQ2YjJiYTJmMDRmZmY0YjIiLCJuYW1lIjoiTHVrYXMiLCJzdXJuYW1lIjoiS3J1cGVua2luYXMiLCJhZ2UiOjIyLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHVGVXdnMnRNNTlPQVB5QnNYUlZyb09yUld3RXJQS2JJRDExT0NpSWhNdkRQWi4yS1ZGTVBPIiwiYWRtaW4iOnRydWUsImlhdCI6MTU3NTgzNTQ3MSwiZXhwIjoxNTc1ODM1ODMxfQ.YcH9S4Cv3EUUbGbM8ulswLmE_sqXZyZHB63DelEpwHs
Content-Type: application/json

{
    "title": "Kuponas 3",
    "place": "2",
    "value": "400000",
    "about": "Prekybos centre maxima",
    "fk_contestid": "5de406d9c9fcbb3380e097e8"
}

### Delete prize by id
DELETE http://localhost:3000/prizes/5de40707c9fcbb3380e097ea
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGQ5MTc1MTQ2YjJiYTJmMDRmZmY0YjIiLCJuYW1lIjoiTHVrYXMiLCJzdXJuYW1lIjoiS3J1cGVua2luYXMiLCJhZ2UiOjIyLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHVGVXdnMnRNNTlPQVB5QnNYUlZyb09yUld3RXJQS2JJRDExT0NpSWhNdkRQWi4yS1ZGTVBPIiwiYWRtaW4iOnRydWUsImlhdCI6MTU3NTgzNTQ3MSwiZXhwIjoxNTc1ODM1ODMxfQ.YcH9S4Cv3EUUbGbM8ulswLmE_sqXZyZHB63DelEpwHs

### Update prize by id
PATCH http://localhost:3000/prizes/5de40707c9fcbb3380e097ea
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGQ5MTc1MTQ2YjJiYTJmMDRmZmY0YjIiLCJuYW1lIjoiTHVrYXMiLCJzdXJuYW1lIjoiS3J1cGVua2luYXMiLCJhZ2UiOjIyLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHVGVXdnMnRNNTlPQVB5QnNYUlZyb09yUld3RXJQS2JJRDExT0NpSWhNdkRQWi4yS1ZGTVBPIiwiYWRtaW4iOnRydWUsImlhdCI6MTU3NTgzNTQ3MSwiZXhwIjoxNTc1ODM1ODMxfQ.YcH9S4Cv3EUUbGbM8ulswLmE_sqXZyZHB63DelEpwHs
Content-Type: application/json

{
    "title": "Čekis",
    "place": "2",
    "value": "20"
}